### PR TITLE
Fixed excessive warnings in the console

### LINKED ISSUE #142: Mountains of errors/warnings in the console
There shouldn't be so many errors and warnings in the console. Some of them look easily fixable. These need to be cleaned up.

### PR DESCRIPTION
**Pull request by KrashLeviathan**
Closes #142 

- Removed all connect decorators.
- Added keys to each type of iterative render.
- Wrapped tabs in div.
- Redux only logs in non-production env.
- Some required props were taking null value, so I made them optional and gave default values of null.
- Removed dash from styles attribute.
- Removed `<ul>` from being nested in `<p>`
- Other fixes.

### CODE REVIEW

File: coruscant/src/components/ProjectLinks.js [hunk 1]
```diff
@@ -39,10 +39,16 @@ class ProjectLinks extends React.PureComponent {
   }
 }
 
+ProjectLinks.defaultProps = {
+  githubUrl: null,
```
Comment (nischayv) [inline coruscant/src/components/ProjectLinks.js]: Since you are removing isRequired, does the component handle null props properly? Like will it break if props were null?

File: coruscant/src/containers/ProjectBuilds.js [hunk 2]
```diff
@@ -159,11 +158,19 @@ class ProjectBuilds extends Component {
   }
 }
 
+ProjectBuilds.defaultProps = {
+  travisUrl: null
```
Comment (nischayv) [inline coruscant/src/containers/ProjectBuilds.js]: Will the component handle case for null props?

File: coruscant/src/containers/ProjectIssues.js [hunk 3]
```diff
@@ -146,11 +145,19 @@ class ProjectIssues extends Component {
   }
 }
 
+ProjectIssues.defaultProps = {
+  githubUrl: null
```
Comment (nischayv) [inline coruscant/src/containers/ProjectIssues.js]: Will the component handle case for null props?

File: coruscant/src/store/index.js [hunk 4]
```diff
@@ -5,18 +5,20 @@ import { createLogger } from 'redux-logger'
...
 import { loadState } from './../utils/localStorage'
 
-const loggerMiddleware = createLogger()
 // eslint-disable-next-line no-underscore-dangle
 const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose
 const persistedState = loadState()
 
+// The logger middleware is only included in non-production environments
+const isProductionEnvironment = (process.env.NODE_ENV === 'production')
+const middlewares = (isProductionEnvironment)
```
Comment (nischayv) [inline coruscant/src/store/index.js]: Thanks for this!

File: coruscant/src/components/ProjectLinks.js (hunk 1 above)
Comment (nischayv) [reply coruscant/src/components/ProjectLinks.js]: nvm just saw this - Some required props were taking null value, so I made them optional and gave default values of null.
